-- v1.0.29 — adaptive strategy risk, EA capability handshake, automatic
-- position management, and realized MFE/MAE/exit-quality telemetry.

alter table public.mt5_terminals
  add column if not exists ea_version text;

alter table public.strategies
  add column if not exists risk_percent numeric(6,3) not null default 0.500
    check (risk_percent > 0 and risk_percent <= 5);

update public.strategies
set risk_percent = 0.350
where kind = 'confirmed_trend_pullback' and risk_percent = 0.500;

alter table public.signals
  add column if not exists suggested_risk_percent numeric(6,3),
  add column if not exists entry_atr numeric,
  add column if not exists entry_spread_points numeric,
  add column if not exists initial_risk_distance numeric;

alter table public.ea_commands
  add column if not exists risk_percent numeric(6,3),
  add column if not exists entry_atr numeric,
  add column if not exists entry_spread_points numeric,
  add column if not exists initial_risk_distance numeric,
  add column if not exists auto_manage boolean not null default false,
  add column if not exists management_stage integer,
  add column if not exists management_source_bar_time timestamptz;

alter table public.positions
  add column if not exists initial_sl numeric,
  add column if not exists initial_tp numeric,
  add column if not exists initial_risk_distance numeric,
  add column if not exists risk_percent numeric(6,3),
  add column if not exists entry_atr numeric,
  add column if not exists entry_spread_points numeric,
  add column if not exists mfe_price_distance numeric not null default 0,
  add column if not exists mae_price_distance numeric not null default 0,
  add column if not exists mfe_r numeric not null default 0,
  add column if not exists mae_r numeric not null default 0,
  add column if not exists max_unrealized_pl numeric,
  add column if not exists min_unrealized_pl numeric,
  add column if not exists auto_manage boolean not null default false,
  add column if not exists management_stage integer not null default 0,
  add column if not exists last_management_bar_time timestamptz;

alter table public.trade_history
  add column if not exists initial_sl numeric,
  add column if not exists initial_tp numeric,
  add column if not exists initial_risk_distance numeric,
  add column if not exists risk_percent numeric(6,3),
  add column if not exists entry_atr numeric,
  add column if not exists entry_spread_points numeric,
  add column if not exists mfe_price_distance numeric,
  add column if not exists mae_price_distance numeric,
  add column if not exists mfe_r numeric,
  add column if not exists mae_r numeric,
  add column if not exists max_unrealized_pl numeric,
  add column if not exists min_unrealized_pl numeric;

alter table public.trade_history
  drop constraint if exists trade_history_close_reason_check;
alter table public.trade_history
  add constraint trade_history_close_reason_check check (
    close_reason is null or close_reason = any (array[
      'tp','sl','manual','agent','eod_flat','basket_flatten',
      'ea_local_hard_stop','stop_out','rollover','other',
      'reconciled_missing_ea_report'
    ])
  );

comment on column public.strategies.risk_percent is
  'Maximum account-balance percentage at risk across all legs generated by one strategy signal.';
comment on column public.positions.mfe_r is
  'Maximum favorable price excursion divided by immutable initial stop distance.';
comment on column public.positions.mae_r is
  'Maximum adverse price excursion divided by immutable initial stop distance.';
comment on column public.mt5_terminals.ea_version is
  'EA-reported semantic version used to gate capabilities such as broker-native risk sizing.';

